USER_PARAMS_MISSING = "error: missing or invalid parameter info or missing Satori Auth Token, check your data"
print_find_db = "\n\nFINDING LOCATION RECORDS FOR DATABASE: "
print_querytext = "queried the enclosing table and found these results: \n\n"
print_foundemail = "found email located at: "
print_noqueryresults = "no query was run: datasource type not implemented yet - still building remediation using Satori locations"